bouquetapp/urls.py
from django.urls import path
from django.conf.urls import include
from bouquetapp import views
from .views import *

app_name = "bouquetapp"

urlpatterns = [
    path('', home, name='home'),
    path('bouquetform/', create_bouquet_form, name='create_bouquet_form'),
    path('bouquet/<int:bouquet_id>/details', )
]

flowershop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bouquetapp.urls'))
]

bouquetapp/models/bouquet.py
from django.db import models
from django.urls import reverse


class Bouquet(models.Model):

    name = models.CharField(max_length=100)
    occasion = models.CharField(max_length=100)
    flowers = models.ManyToManyField("Flower", through='BouquetFlower')

    class Meta:
        verbose_name = ("Bouquet")
        verbose_name_plural = ("Bouquets")

    def __str__(self):
        return f"{self.name} ({self.occasion})"

    def get_absolute_url(self):
        return reverse("Bouquet_detail", kwargs={"pk": self.pk})

bouquetapp/models/bouquet_flower.py
from django.db import models


class BouquetFlower(models.Model):

    flower = models.ForeignKey("Flower", on_delete=models.CASCADE)
    bouquet = models.ForeignKey("Bouquet", on_delete=models.CASCADE)
    quantity = models.IntegerField()

bouquetapp/models/flower.py
from django.db import models
from django.urls import reverse


class Flower(models.Model):

    name = models.CharField(max_length=100)
    binomial_name = models.CharField(max_length=100)
    longevity_in_days = models.IntegerField()
    bouquets = models.ManyToManyField("Bouquet", through='BouquetFlower')

    class Meta:
        verbose_name = ("Flower")
        verbose_name_plural = ("Flowers")

    def __str__(self):
        return f"{self.name} ({self.binomial_name})"

    def get_absolute_url(self):
        return reverse("Flower_detail", kwargs={"pk": self.pk})

bouquetapp/models/model_factory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

bouquetapp/views/home.py
import sqlite3
from django.shortcuts import render, redirect, reverse
from bouquetapp.models import Bouquet, model_factory
from .connection import Connection

def home(request):
    if request.method == 'GET':
        with sqlite3.connect(Connection.db_path) as conn:
            conn.row_factory = model_factory(Bouquet)
            db_cursor = conn.cursor()
            db_cursor.execute(""" 
                SELECT
                    b.id,
                    b.name,
                    b.occasion
                    FROM bouquetapp_bouquet b
                    ORDER BY b.name;
                """)

            bouquet_data = db_cursor.fetchall()

            template = 'home.html'
            context = {
                'bouquet_data' : bouquet_data
            }

            return render(request, template, context)

    elif request.method == 'POST':
        form_data = request.POST
        with sqlite3.connect(Connection.db_path) as conn:
            db_cursor = conn.cursor()
            db_cursor.execute("""
            INSERT INTO bouquetapp_bouquet
            (name, occasion
            )
            VALUES (?, ?)
            """,
                (form_data['name'], form_data['occasion']))
        return redirect(reverse('bouquetapp:home'))        

bouquetapp/templates/bouquets/bouquet_form.html
{% extends 'shared/base.html' %}
{% load static %}


{% block content %}

<body>
    <h1>Bouquet Form</h1>

    <form action="{% url 'bouquetapp:home' %}" method="post">
    {% csrf_token %}
        
        <fieldset>
            <label for="name">Name: </label>
            <input id="name" type="text" name="name">
        </fieldset>     
        <fieldset>
            <label for="occasion">Occasion: </label>
            <input id="occasion" type="text" name="occasion">
        </fieldset>

        <input class="new_form" type="submit" value="Create" />     

    </form>    
</body>
{% endblock %}    

bouquetapp/templates/home.html
{% extends 'shared/base.html' %}
{% load static %}

{% block content %}
<h1>Fancy Flowershop</h1>

<a href="{% url 'bouquetapp:create_bouquet_form' %}">Add new bouquet</a>
<ol>
    {% for bouquet in bouquet_data %}
        <li>{{ bouquet.name }}</li>
    {% endfor %}   
</ol>
{% endblock content %}

bouquetapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Fancy Flowershop</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    {% comment %} <link rel="stylesheet" href="{% static 'styles/base.css' %}" type="text/css" media="screen" /> {% endcomment %}
    {% comment %} <link rel="stylesheet" href="{% static 'styles/login.css' %}" type="text/css" media="screen" /> {% endcomment %}
    {% comment %} <link rel="stylesheet" href="{% static 'styles/comp_modal.css' %}" type="text/css" media="screen" /> {% endcomment %}
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    {% block css %}
    {% endblock %}
</head>

<body>


    

    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #16a085;">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bouquetapp:home' %}">Home</a>
                </li>
                {% comment %} <li class="nav-item">
                    <a class="nav-link" href="{% url 'bouquetapp:employee_list' %}"> Employees</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bouquetapp:departments' %}">Departments</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bouquetapp:computers' %}">Computers</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bouquetapp:trainingprograms' %}"> Training Programs</a>
                </li> {% endcomment %}
                
                
            </ul>
            {% comment %} <ul class="navbar-nav mr-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bouquetapp:logout' %}"> Logout</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bouquetapp:login' %}">Login</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bouquetapp:admin' %}">Django Admin</a>
                </li>
            </ul> {% endcomment %}
        </div>
    </nav>
   
    


    <main class="main-content">
        {% block content %}
        {% endblock %}
    </main>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    {%block scripts%}
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    {% endblock scripts %}

</body>

</html>